AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  # The name of the bucket where all the lambdas are, if any.. this gets injected from the pipeline tool
  LambdaBucket:
    Type: String
  # Lambdas Zip version below
  SampleFuncZip:
    Type: String

Resources:
  HttpApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: Happiness Event POST
      Description: Allows one to POST their happiness rating
      ProtocolType: HTTP
      Target: arn:aws:apigateway:{region}:lambda:path/2015-03-31/functions/arn:aws:lambda:{region}:{account-id}:function:{function-name}/invocations

