name: build
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Lint project
        run: build/go-lint.sh

      - name: Test project
        run: build/go-test.sh

      - name: Build lambdas
        run: build/zip.sh

      - name: Upload lambdas
        run: |
          # https://github.com/actions/setup-go/issues/14
          export PATH=${PATH}:`go env GOPATH`/bin
          go get -u github.com/raymonstah/aws-pipeline
          aws-pipeline lambda --bucket $BUCKET --target-path $LAMBDA_DIRECTORY
        env:
          BUCKET: grapefulLambdas
          LAMBDA_DIRECTORY: target/
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}


    services:
      # smh https://github.community/t5/GitHub-Actions/Github-Actions-services-not-reachable/td-p/30050
      dynamodb:
        image: amazon/dynamodb-local:latest
        options: --workdir /home/dynamodblocal
        ports:
          - 8000:8000